const Map<String, String> appStringsEn = <String, String>{
  'Account': 'Account',
  'Account saved.': 'Account saved.',
  'Add widget': 'Add widget',
  'Add': 'Add',
  'Add all ({count})': 'Add all ({count})',
  'Add device': 'Add device',
  'Add port': 'Add port',
  'Admin access required.': 'Admin access required.',
  'Admin account': 'Admin account',
  'Admin email': 'Admin email',
  'Allow creating devices': 'Allow creating devices',
  'App': 'App',
  'App appearance and language': 'App appearance and language',
  'At least 10 characters': 'At least 10 characters',
  'Avatar': 'Avatar',
  'Cancel': 'Cancel',
  'Change password': 'Change password',
  'Change server': 'Change server',
  'Change the target UpSnap server for this client.':
      'Change the target UpSnap server for this client.',
  'Confirm': 'Confirm',
  'Confirm the launcher prompt to place the widget.':
      'Confirm the launcher prompt to place the widget.',
  'Confirm password': 'Confirm password',
  'Connect to UpSnap': 'Connect to UpSnap',
  'Connection': 'Connection',
  'Create admin': 'Create admin',
  'Create the initial admin account to complete the first-run setup.':
      'Create the initial admin account to complete the first-run setup.',
  'Create user': 'Create user',
  'Creating admin...': 'Creating admin...',
  'Current password': 'Current password',
  'Dark': 'Dark',
  'Delete': 'Delete',
  'Delete {name}?': 'Delete {name}?',
  'Description': 'Description',
  'Device link': 'Device link',
  'Device permissions': 'Device permissions',
  'Devices': 'Devices',
  'Edit Device': 'Edit Device',
  'Edit device': 'Edit device',
  'Email or username': 'Email or username',
  'Enable Sleep-On-LAN': 'Enable Sleep-On-LAN',
  'Enable lazy ping': 'Enable lazy ping',
  'Enable shutdown schedule': 'Enable shutdown schedule',
  'Enable wake schedule': 'Enable wake schedule',
  'English': 'English',
  'Enter the base URL of your UpSnap server. HTTP on a local network is supported.':
      'Enter the base URL of your UpSnap server. HTTP on a local network is supported.',
  'Enter a valid email address': 'Enter a valid email address',
  'Examples: `http://upsnap.local:8090`, `https://myserver.example.com`':
      'Examples: `http://upsnap.local:8090`, `https://myserver.example.com`',
  'Follow system': 'Follow system',
  'General': 'General',
  'Group by collections': 'Group by collections',
  'Groups': 'Groups',
  'IP': 'IP',
  'IP address': 'IP address',
  'Include devices named "Unknown"': 'Include devices named "Unknown"',
  'Japanese': 'Japanese',
  'Language': 'Language',
  'Light': 'Light',
  'Link': 'Link',
  'Logout': 'Logout',
  'MAC address': 'MAC address',
  'MAC: {value}': 'MAC: {value}',
  'Manage server-wide settings from the mobile client.':
      'Manage server-wide settings from the mobile client.',
  'Manual': 'Manual',
  'Name': 'Name',
  'Netmask': 'Netmask',
  'Netmask: {value}': 'Netmask: {value}',
  'Network Scan': 'Network Scan',
  'Network scan range': 'Network scan range',
  'New Device': 'New Device',
  'New group': 'New group',
  'New netmask': 'New netmask',
  'New password': 'New password',
  'New port': 'New port',
  'No': 'No',
  'No active account.': 'No active account.',
  'No devices are available for your account.':
      'No devices are available for your account.',
  'No devices yet. Use the button below to add your first machine.':
      'No devices yet. Use the button below to add your first machine.',
  'No scan results yet.': 'No scan results yet.',
  'No schedule': 'No schedule',
  'No shutdown command configured.': 'No shutdown command configured.',
  'Offline': 'Offline',
  'Online': 'Online',
  'Open externally': 'Open externally',
  'Open immediately': 'Open immediately',
  'Open link after wake': 'Open link after wake',
  'Password': 'Password',
  'Password changed. Please sign in again.':
      'Password changed. Please sign in again.',
  'Passwords do not match': 'Passwords do not match',
  'Passwords do not match.': 'Passwords do not match.',
  'Pending': 'Pending',
  'Permissions saved for {username}.': 'Permissions saved for {username}.',
  'Ping': 'Ping',
  'Ping command override': 'Ping command override',
  'Ping interval cron': 'Ping interval cron',
  'Ping interval cron is invalid.': 'Ping interval cron is invalid.',
  'Port {number}': 'Port {number}',
  'Port number': 'Port number',
  'Ports': 'Ports',
  'Power': 'Power',
  'Profile': 'Profile',
  'Read': 'Read',
  'Refresh': 'Refresh',
  'Reboot': 'Reboot',
  'Reboot {name}?': 'Reboot {name}?',
  'Replace scanned netmask': 'Replace scanned netmask',
  'Required': 'Required',
  'Require authorization': 'Require authorization',
  'Require shutdown confirmation': 'Require shutdown confirmation',
  'Require wake confirmation': 'Require wake confirmation',
  'Retry': 'Retry',
  'SOL password': 'SOL password',
  'SOL user': 'SOL user',
  'Save': 'Save',
  'Saving...': 'Saving...',
  'Save account': 'Save account',
  'Save and connect': 'Save and connect',
  'Save connection': 'Save connection',
  'Save range': 'Save range',
  'Save server settings': 'Save server settings',
  'Scan': 'Scan',
  'Scan range': 'Scan range',
  'Scan range saved.': 'Scan range saved.',
  'Scanning...': 'Scanning...',
  'Added': 'Added',
  'Search devices': 'Search devices',
  'Select favicon': 'Select favicon',
  'Server': 'Server',
  'Server URL': 'Server URL',
  'Set up {appName}': 'Set up {appName}',
  'Settings': 'Settings',
  'Settings saved.': 'Settings saved.',
  'Shutdown': 'Shutdown',
  'Shutdown {name}?': 'Shutdown {name}?',
  'Shutdown cron': 'Shutdown cron',
  'Shutdown cron is invalid.': 'Shutdown cron is invalid.',
  'Shutdown command': 'Shutdown command',
  'Shutdown timeout (seconds)': 'Shutdown timeout (seconds)',
  'Sign in': 'Sign in',
  'Sign in with your admin or user account.':
      'Sign in with your admin or user account.',
  'Signing in...': 'Signing in...',
  'Sleep': 'Sleep',
  'Sleep-On-LAN': 'Sleep-On-LAN',
  'Sleep-On-LAN port': 'Sleep-On-LAN port',
  'Starting {appName}...': 'Starting {appName}...',
  'System default': 'System default',
  'Theme': 'Theme',
  'This changes only this client app.': 'This changes only this client app.',
  'Unknown': 'Unknown',
  'Update': 'Update',
  'Update the password for the current account.':
      'Update the password for the current account.',
  'Updated {date}': 'Updated {date}',
  'User account': 'User account',
  'User created.': 'User created.',
  'User deleted.': 'User deleted.',
  'Username': 'Username',
  'Users': 'Users',
  'Vendor: {value}': 'Vendor: {value}',
  'Wake': 'Wake',
  'Wake Password': 'Wake Password',
  'Wake cron': 'Wake cron',
  'Wake cron is invalid.': 'Wake cron is invalid.',
  'Wake group': 'Wake group',
  'Wake password': 'Wake password',
  'Wake timeout (seconds)': 'Wake timeout (seconds)',
  'Wake {name}?': 'Wake {name}?',
  'Website title': 'Website title',
  'Widget pinning is not available here.':
      'Widget pinning is not available here.',
  '{name} added.': '{name} added.',
};
