const Map<String, String> appStringsJa = <String, String>{
  'Account': 'アカウント',
  'Account saved.': 'アカウントを保存しました。',
  'Add widget': 'ウィジェットを追加',
  'Add': '追加',
  'Add all ({count})': 'すべて追加（{count}件）',
  'Add device': '機器を追加',
  'Add port': 'ポートを追加',
  'Admin access required.': '管理者権限が必要です。',
  'Admin account': '管理者アカウント',
  'Admin email': '管理者メールアドレス',
  'Allow creating devices': '機器の作成を許可',
  'App': 'アプリ',
  'App appearance and language': '表示テーマと言語',
  'At least 10 characters': '10文字以上で入力してください',
  'Avatar': 'アバター',
  'Cancel': 'キャンセル',
  'Change password': 'パスワードを変更',
  'Change server': 'サーバーを変更',
  'Change the target UpSnap server for this client.':
      'このクライアントが接続する UpSnap サーバーを変更します。',
  'Confirm': '確認',
  'Confirm the launcher prompt to place the widget.':
      'ランチャーの確認画面でウィジェットを配置してください。',
  'Choose widget style': 'ウィジェットの種類を選択',
  'Confirm password': 'パスワード確認',
  'Connect to UpSnap': 'UpSnap に接続',
  'Connection': '接続',
  'Create admin': '管理者を作成',
  'Create the initial admin account to complete the first-run setup.':
      '初回セットアップを完了するため、最初の管理者アカウントを作成してください。',
  'Create user': 'ユーザーを作成',
  'Creating admin...': '管理者を作成中...',
  'Current password': '現在のパスワード',
  'Dark': 'ダーク',
  'Delete': '削除',
  'Delete {name}?': '{name} を削除しますか？',
  'Description': '説明',
  'Device link': '機器リンク',
  'Device permissions': '機器権限',
  'Devices': '機器',
  'Edit Device': '機器を編集',
  'Edit device': '機器を編集',
  'Email or username': 'メールアドレスまたはユーザー名',
  'Enable Sleep-On-LAN': 'Sleep-On-LAN を有効化',
  'Enable lazy ping': 'Lazy ping を有効化',
  'Enable shutdown schedule': 'シャットダウンスケジュールを有効化',
  'Enable wake schedule': '起動スケジュールを有効化',
  'English': '英語',
  'Enter the base URL of your UpSnap server. HTTP on a local network is supported.':
      'UpSnap サーバーのベース URL を入力してください。ローカルネットワーク上の HTTP も利用できます。',
  'Enter a valid email address': '有効なメールアドレスを入力してください',
  'Examples: `http://upsnap.local:8090`, `https://myserver.example.com`':
      '例: `http://upsnap.local:8090`, `https://myserver.example.com`',
  'Follow system': 'システムに従う',
  'General': '基本',
  'Group by collections': 'コレクションごとに表示',
  'Groups': 'グループ',
  'IP': 'IP',
  'IP address': 'IP アドレス',
  'Include devices named "Unknown"': '名前が "Unknown" の機器も含める',
  'Japanese': '日本語',
  'Language': '言語',
  'Light': 'ライト',
  'Link': 'リンク',
  'Logout': 'ログアウト',
  'MAC address': 'MAC アドレス',
  'MAC: {value}': 'MAC: {value}',
  'Manage server-wide settings from the mobile client.':
      'モバイルクライアントからサーバー全体の設定を変更します。',
  'Manual': '手動',
  'Name': '名前',
  'Netmask': 'ネットマスク',
  'Netmask: {value}': 'ネットマスク: {value}',
  'Network Scan': 'ネットワークスキャン',
  'Network scan range': 'ネットワークスキャン範囲',
  'New Device': '新しい機器',
  'New group': '新しいグループ',
  'New netmask': '新しいネットマスク',
  'New password': '新しいパスワード',
  'New port': '新しいポート',
  'No': 'なし',
  'No active account.': '有効なアカウントがありません。',
  'No devices are available for your account.': 'このアカウントで利用できる機器はありません。',
  'No devices yet. Use the button below to add your first machine.':
      '機器はまだありません。下のボタンから最初の機器を追加してください。',
  'No scan results yet.': 'まだスキャン結果がありません。',
  'No schedule': 'スケジュールなし',
  'No shutdown command configured.': 'シャットダウンコマンドが設定されていません。',
  'Offline': 'オフライン',
  'Online': 'オンライン',
  'Open externally': '外部で開く',
  'Open immediately': 'すぐに開く',
  'Open link after wake': '起動後にリンクを開く',
  'Password': 'パスワード',
  'Password changed. Please sign in again.': 'パスワードを変更しました。再度サインインしてください。',
  'Passwords do not match': 'パスワードが一致しません',
  'Passwords do not match.': 'パスワードが一致しません。',
  'Pending': '処理中',
  'Permissions saved for {username}.': '{username} の権限を保存しました。',
  'Ping': 'Ping',
  'Ping command override': 'Ping コマンド上書き',
  'Ping interval cron': 'Ping 間隔 cron',
  'Ping interval cron is invalid.': 'Ping 間隔の cron が不正です。',
  'Port {number}': 'ポート {number}',
  'Port number': 'ポート番号',
  'Ports': 'ポート',
  'Power': '電源',
  'Power icon only': '電源アイコンのみ',
  'Profile': 'プロフィール',
  'Read': '参照',
  'Refresh': '更新',
  'Reboot': '再起動',
  'Reboot {name}?': '{name} を再起動しますか？',
  'Replace scanned netmask': 'スキャン結果のネットマスクを置換',
  'Required': '必須です',
  'Require authorization': '認証を必須にする',
  'Require shutdown confirmation': 'シャットダウン確認を必須にする',
  'Require wake confirmation': '起動確認を必須にする',
  'Retry': '再試行',
  'SOL password': 'SOL パスワード',
  'SOL user': 'SOL ユーザー',
  'Save': '保存',
  'Saving...': '保存中...',
  'Save account': 'アカウントを保存',
  'Save and connect': '保存して接続',
  'Save connection': '接続先を保存',
  'Save range': '範囲を保存',
  'Save server settings': 'サーバー設定を保存',
  'Scan': 'スキャン',
  'Scan range': 'スキャン範囲',
  'Scan range saved.': 'スキャン範囲を保存しました。',
  'Scanning...': 'スキャン中...',
  'Added': '追加済み',
  'Search devices': '機器を検索',
  'Select favicon': 'favicon を選択',
  'Select how the Android widget should look.': 'Android ウィジェットの見た目を選択してください。',
  'Server': 'サーバー',
  'Server URL': 'サーバー URL',
  'Set up {appName}': '{appName} をセットアップ',
  'Settings': '設定',
  'Settings saved.': '設定を保存しました。',
  'Shutdown': 'シャットダウン',
  'Shutdown {name}?': '{name} をシャットダウンしますか？',
  'Shutdown cron': 'シャットダウン cron',
  'Shutdown cron is invalid.': 'シャットダウン cron が不正です。',
  'Shutdown command': 'シャットダウンコマンド',
  'Shutdown timeout (seconds)': 'シャットダウン待機時間（秒）',
  'Sign in': 'サインイン',
  'Sign in with your admin or user account.': '管理者またはユーザーアカウントでサインインしてください。',
  'Signing in...': 'サインイン中...',
  'Sleep': 'スリープ',
  'Sleep-On-LAN': 'Sleep-On-LAN',
  'Sleep-On-LAN port': 'Sleep-On-LAN ポート',
  'Starting {appName}...': '{appName} を起動しています...',
  'System default': 'システム設定',
  'Theme': 'テーマ',
  'This changes only this client app.': 'この変更はこのクライアントアプリにのみ適用されます。',
  'Unknown': '不明',
  'Update': '更新',
  'Update the password for the current account.': '現在のアカウントのパスワードを更新します。',
  'Updated {date}': '{date} に更新',
  'User account': 'ユーザーアカウント',
  'User created.': 'ユーザーを作成しました。',
  'User deleted.': 'ユーザーを削除しました。',
  'Username': 'ユーザー名',
  'Users': 'ユーザー',
  'Vendor: {value}': 'ベンダー: {value}',
  'Wake': '起動',
  'Wake Password': 'Wake パスワード',
  'Wake cron': '起動 cron',
  'Wake cron is invalid.': '起動 cron が不正です。',
  'Wake group': 'グループを起動',
  'Wake password': 'Wake パスワード',
  'Wake timeout (seconds)': '起動待機時間（秒）',
  'Wake {name}?': '{name} を起動しますか？',
  'Website title': 'Web サイト名',
  'Widget with device name': '機器名付きウィジェット',
  'Widget pinning is not available here.': 'この環境ではウィジェット追加に対応していません。',
  'Shows the device name and current status.': '機器名と現在の状態を表示します。',
  'Shows only the power button with status color.': '状態色付きの電源ボタンのみを表示します。',
  '{name} added.': '{name} を追加しました。',
};
